# Generated by Django 4.0.3 on 2023-02-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profession',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Job Holder', 'Job Holder'), ('businessman', 'businessman'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
