# Generated by Django 4.0.3 on 2023-02-24 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0002_alter_userinformation_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('descriptiion', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('additional_information', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='organization images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user images'),
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Bootcamp', 'Bootcamp'), ('Workshop', 'Workshop'), ('Others', 'Others')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, default='Technology', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, max_length=100, null=True)),
                ('seat', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seminar.organization')),
            ],
        ),
    ]
