# Generated by Django 4.0.3 on 2023-02-25 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_alter_organization_link_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='length',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
