# Generated by Django 4.0.3 on 2023-02-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_alter_seminar_length_alter_seminar_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seminar images'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
