# Generated by Django 4.0.3 on 2023-03-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_seminar_image_userinformation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
