# Generated by Django 4.0.3 on 2023-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_seminar_end_time_seminar_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='end_time',
            field=models.TimeField(blank=True, default='Not Mentioned', null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_time',
            field=models.TimeField(blank=True, default='Not Mentioned', null=True),
        ),
    ]
