# Generated by Django 4.0.3 on 2023-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0008_alter_seminar_end_time_alter_seminar_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
