# Generated by Django 4.0.3 on 2023-03-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0009_alter_seminar_end_date_alter_seminar_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('can_add_seminar', 'can add seminar'),)},
        ),
    ]
