# Generated by Django 4.0.3 on 2023-11-18 18:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0011_seminar_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='archive',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
